language: csharp
solution: ./SpeakerMeet.sln 
dist: bionic
mono: none
dotnet: 5.0
install: 
    - dotnet restore
script:
    - dotnet build
    - dotnet test ./SpeakerMeet.API.Tests/SpeakerMeet.API.Tests.csproj
