language: csharp
solution: ./SpeakerMeet.sln 
dist: bionic
mono: none
dotnet: 5.0
install: 
    - dotnet restore ./SpeakerMeet.API/SpeakerMeet.API.csproj
script:
    - dotnet build ./SpeakerMeet.API/SpeakerMeet.API.csproj
    - dotnet test ./SpeakerMeet.API.Tests/SpeakerMeet.API.Tests.csproj
